# PS IN1 320 LAB02
# Maciej Lewicki
# lm34410@zut.edu.pl

CC = gcc
OBJFILE = main.o
TARGET = lab02

all: $(TARGET)
$(TARGET): $(OBJFILE)
	$(CC) -o $(TARGET) $(OBJFILE)

clean:
	rm -f $(OBJFILES) $(TARGET) 
